Description: Pattern with packages for f8132 configurations
Name: jolla-configuration-f8132
Requires:
- pattern:jolla-hw-adaptation-dora

- droid-config-f8132-sailfish
- droid-config-f8132-pulseaudio-settings
- droid-config-f8132-policy-settings
- droid-config-f8132-preinit-plugin
- droid-config-f8132-flashing
- droid-config-f8132-bluez5
- droid-hal-version-f8132

Summary: Jolla Configuration f8132
